title: Silly Station 14
description: Blehhhhhh :3

# Build settings


tailwindcss:
  css_path: "./_tailwind.css" # this is the default location

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: minima
plugins:
  - jekyll-feed
  - jekyll-tailwindcss

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
